#!/usr/bin/env php
<?php

use Symfony\Component\Console\Input\ArgvInput;
use Syno\Application;
use Syno\ConsoleApplication;

require __DIR__.'/vendor/autoload.php';

$input = new ArgvInput();
$env = $input->getParameterOption(array('--env', '-e'), 'dev');
$debug = !$input->hasParameterOption(array('--no-debug', '')) && $env !== 'prod';

if ('dev' === $env) {
    $configFile = __DIR__.'/config/dev.php.dist';
    if (is_file(__DIR__.'/config/dev.php')) {
        $configFile = __DIR__.'/config/dev.php';
    }
} else {
    $configFile = __DIR__.'/config/'.$env.'.php';
}

$console = new ConsoleApplication(
    new Application($env, $debug)
);
require __DIR__.'/src/commands.php';
$console->run($input);
