#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

$app = require __DIR__.'/src/app.php';
require __DIR__.'/config.php';

$console = require __DIR__.'/src/console.php';
$console->run();
